In [35]:
import numpy as np

X = [[1, 2, 3, 4],
    [2, 3, 4, 5],
    [2, 6, 3, 2]]
"""
inputs = [0, -1, 2, 3, 4, 5, 6]
outputs = []

for i in inputs:
    outputs.append(max(0, i))
print(outputs)

"""

'\ninputs = [0, -1, 2, 3, 4, 5, 6]\noutputs = []\n\nfor i in inputs:\n    outputs.append(max(0, i))\nprint(outputs)\n\n'

In [36]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.outputs = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
    def forward(self, inputs):
        self.outputs = np.maximum(0, inputs)
        
        
layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

layer1.forward(np.array(X))
layer2.forward(layer1.outputs)
layer2.outputs

array([[0.10460608, 0.08663504],
       [0.12402582, 0.11251424],
       [0.02382219, 0.0462729 ]], dtype=float32)

In [37]:
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

X, y = spiral_data(100, 3)

In [38]:
import seaborn as sns
import matplotlib.pyplot as plt 

In [40]:
layer1 = Layer_Dense(2, 5)
activation1 = Activation_ReLU()

layer1.forward(X)
layer1.outputs

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 5.09662132e-05,  2.82163121e-04, -6.14295888e-04,
        -2.78327265e-04, -2.18806133e-04],
       [-2.53826292e-05,  1.32260774e-03, -1.89793913e-03,
        -1.03709206e-03, -6.62760111e-04],
       ...,
       [ 1.49472691e-02, -1.03460461e-01,  1.00327469e-01,
         6.80047795e-02,  3.40471603e-02],
       [ 1.17370244e-02, -1.04946040e-01,  1.14487566e-01,
         7.24482983e-02,  3.92385311e-02],
       [ 1.57508273e-02, -1.03014432e-01,  9.66713205e-02,
         6.68329149e-02,  3.27085815e-02]], dtype=float32)

In [41]:
activation1.forward(layer1.outputs)

In [42]:
activation1.outputs

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [5.09662132e-05, 2.82163121e-04, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 1.32260774e-03, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       ...,
       [1.49472691e-02, 0.00000000e+00, 1.00327469e-01, 6.80047795e-02,
        3.40471603e-02],
       [1.17370244e-02, 0.00000000e+00, 1.14487566e-01, 7.24482983e-02,
        3.92385311e-02],
       [1.57508273e-02, 0.00000000e+00, 9.66713205e-02, 6.68329149e-02,
        3.27085815e-02]], dtype=float32)