In [48]:
import numpy as np

inputs = [[1, 2, 3, 2.5], [1, 2, 3, 4], [2, 3, 4, 5]]

weights1 = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.2, 0.33],
           [0.2, 0.3, 0.34, 0.44]]

biases1 = [2, 3, 0.5]

weights2 = [[0.2, 0.8, -0.2],
           [0.5, -0.91, 0.2],
           [0.2, 0.3, 0.34]]

biases2 = [2, 3, 0.5]

layer1_outputs = np.dot(np.array(inputs), np.array(weights1).T) + biases1

In [49]:
layer1_outputs

array([[4.8  , 3.105, 3.42 ],
       [6.3  , 3.6  , 4.08 ],
       [7.8  , 3.72 , 5.36 ]])

In [50]:
np.array(inputs)

array([[1. , 2. , 3. , 2.5],
       [1. , 2. , 3. , 4. ],
       [2. , 3. , 4. , 5. ]])

In [51]:
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + np.array(biases2)

In [52]:
layer2_outputs

array([[4.76   , 3.25845, 3.5543 ],
       [5.324  , 3.69   , 4.2272 ],
       [5.464  , 4.5868 , 4.9984 ]])

In [54]:
weights3 = [[0.2, 0.8, -0.2],
           [0.5, -0.91, 0.2],
           [0.2, 0.3, 0.34]]

biases3 = [2, 3, 0.5]

layer3_outputs = np.dot(layer2_outputs, np.array(weights3).T) + np.array(biases3)
